### ISSUE TITLE
what is your python version

### ISSUE THREAD

**Issue by Nozdormu-Timer** [NapierNLP/CAPE#1]

**Comment by Nozdormu-Timer** [comment]
And when I try to install requirements, it seems these package versions have conflicting dependencies.

**Comment by richplant** [comment]
3.8.5

**Comment by richplant** [comment]
Packages bumped in #b4d3e14

**Comment by Nozdormu-Timer** [comment]
Thank you. And the parameter local_files_only should be False for the first time to run this model when preparing data.
